# coding: utf-8

"""
    API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest
import swagger_client
import json
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_users(self):
        """Test case for get_users

        """
        api_instance = swagger_client.DefaultApi(swagger_client.ApiClient())

        try:
            users = api_instance.get_users()
        except ApiException as e:
            print("Exception when calling DefaultApi->get_users: %s\n" % e)
        print(json.dumps(users, indent=4))
        pass

    def test_get_users_api_instructions(self):
        """Test case for get_users_api_instructions

        """
        pass

    def test_get_users_by_city(self):
        """Test case for get_users_by_city

        """
        api_instance = swagger_client.DefaultApi(swagger_client.ApiClient())

        try:
            users = api_instance.get_users_by_city("London")
        except ApiException as e:
            print("Exception when calling DefaultApi->get_users: %s\n" % e)
        print(json.dumps(users, indent=4))
        pass

    def test_get_users_by_id(self):
        """Test case for get_users_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
